# Generated by Django 5.2.7 on 2025-10-13 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_from', models.DateField(help_text='The date the borrower wants to pick up the item.', verbose_name='Requested Start Date')),
                ('requested_to', models.DateField(help_text='The date the borrower expects to return the item.', verbose_name='Requested End Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Owner Review'), ('APPROVED', 'Approved by Owner'), ('DENIED', 'Denied by Owner'), ('ON_LOAN', 'Currently on Loan'), ('COMPLETED', 'Completed and Returned'), ('CANCELED', 'Canceled by Borrower')], default='PENDING', max_length=10, verbose_name='Request Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Timestamp')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Return Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_requests', to=settings.AUTH_USER_MODEL, verbose_name='Borrower')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_requests', to='items.item', verbose_name='Requested Item')),
            ],
            options={
                'verbose_name': 'Lending Request',
                'verbose_name_plural': 'Lending Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
