# Generated by Django 5.2.7 on 2025-10-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Owner'), ('DENIED', 'Denied by Owner'), ('COMPLETED', 'Returned and Completed')], default='PENDING', max_length=10, verbose_name='Request Status'),
        ),
    ]
