# messaging/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import MessageViewSet # Assuming this is the name of your viewset

# Initialize the router
router = DefaultRouter()

# Register the MessageViewSet. This creates routes like /messages/ and /messages/{id}/
router.register(r'', MessageViewSet, basename='message') 

urlpatterns = [
    # Include all paths generated by the router
    # Note: Using r'' here means the path will be relative to whatever
    # prefix is given in the main project's urls.py.
    path('', include(router.urls)),
]